language: clojure
lein: 2.7.1
script:
  - lein test
  - lein test :generative
  - lein with-profile recent-clj-test test
  - lein test-cljs
  - lein with-profile +recent-clj test-cljs
# Workaround for https://github.com/travis-ci/travis-ci/issues/4691
sudo: required
jdk:
  - openjdk8
